export const jobCategories = [
  "frontend",
  "backend",
  "fullstack",
  "mobile",
  "devops",
  "design",
  "database",
  "api",
  "testing",
  "other",
];

export const commonTechStack = [
  "React",
  "Next.js",
  "Vue.js",
  "Angular",
  "Node.js",
  "Python",
  "Django",
  "Flask",
  "Ruby on Rails",
  "PHP",
  "Laravel",
  "Java",
  "Spring Boot",
  "C#",
  ".NET",
  "Go",
  "Rust",
  "TypeScript",
  "JavaScript",
  "HTML/CSS",
  "Tailwind CSS",
  "Bootstrap",
  "PostgreSQL",
  "MySQL",
  "MongoDB",
  "Redis",
  "Docker",
  "Kubernetes",
  "AWS",
  "Google Cloud",
  "Azure",
  "Firebase",
  "Supabase",
  "Stripe",
  "Git",
  "GitHub",
  "GitLab",
];

export const commonBudgets = ["0-50", "50-100", "100-150", "150-200", "200+"];

export const commonTools = [
  "All tools",
  "Zapier",
  "Webflow",
  "Airtable",
  "Make",
  "Bubble",
  "Notion",
  "Google Sheets",
  "Shopify",
];

export const timezones = [
  { code: "UTC", value: "UTC" },
  { code: "EST", value: "America/New_York" },
  { code: "CST", value: "America/Chicago" },
  { code: "MST", value: "America/Denver" },
  { code: "PST", value: "America/Los_Angeles" },
  { code: "GMT", value: "Europe/London" },
  { code: "CET", value: "Europe/Paris" },
  { code: "EET", value: "Europe/Athens" },
  { code: "JST", value: "Asia/Tokyo" },
  { code: "CST", value: "Asia/Shanghai" },
  { code: "IST", value: "Asia/Kolkata" },
  { code: "AEST", value: "Australia/Sydney" },
  { code: "NZST", value: "Pacific/Auckland" },
  { code: "BRT", value: "America/Sao_Paulo" },
  { code: "ART", value: "America/Argentina/Buenos_Aires" },
  { code: "SAST", value: "Africa/Johannesburg" },
  { code: "MSK", value: "Europe/Moscow" },
  { code: "IST", value: "Asia/Jerusalem" },
  { code: "GST", value: "Asia/Dubai" },
  { code: "SGT", value: "Asia/Singapore" },
];
