export const jobCategories = [
  "frontend",
  "backend",
  "fullstack",
  "mobile",
  "devops",
  "design",
  "database",
  "api",
  "testing",
  "other",
];

export const commonTechStack = [
  "React",
  "Next.js",
  "Vue.js",
  "Angular",
  "Node.js",
  "Python",
  "Django",
  "Flask",
  "Ruby on Rails",
  "PHP",
  "Laravel",
  "Java",
  "Spring Boot",
  "C#",
  ".NET",
  "Go",
  "Rust",
  "TypeScript",
  "JavaScript",
  "HTML/CSS",
  "Tailwind CSS",
  "Bootstrap",
  "PostgreSQL",
  "MySQL",
  "MongoDB",
  "Redis",
  "Docker",
  "Kubernetes",
  "AWS",
  "Google Cloud",
  "Azure",
  "Firebase",
  "Supabase",
  "Stripe",
  "Git",
  "GitHub",
  "GitLab",
];

export const techStackByCategory = {
  "platform-tools": [
    "Airtable",
    "Bubble",
    "Figma",
    "Framer",
    "Make",
    "Notion",
    "Shopify",
    "Stripe",
    "Webflow",
    "Zapier",
  ],
  "frontend-frameworks": ["Angular", "Next.js", "React", "Vue.js"],
  "backend-frameworks": ["Django", "Flask", "Laravel", "Node.js", "Ruby on Rails", "Spring Boot"],
  "programming-languages": [
    "C#",
    "Go",
    "Java",
    "JavaScript",
    "PHP",
    "Python",
    "Rust",
    "TypeScript",
  ],
  styling: ["Bootstrap", "HTML/CSS", "Tailwind CSS"],
  databases: ["MongoDB", "MySQL", "PostgreSQL", "Redis"],
  "cloud-platforms": ["AWS", "Azure", "Firebase", "Google Cloud", "Supabase"],
  "devops-tools": ["Docker", "Git", "GitHub", "GitLab", "Kubernetes"],
};

export const commonBudgets = ["0-50", "50-100", "100-150", "150-200", "200+"];
export const createTaskFormBudgets = [
  { label: "50", value: "5000" },
  { label: "100", value: "10000" },
  { label: "150", value: "15000" },
  { label: "200", value: "20000" },
];

export const commonTools = [
  "All tools",
  "Zapier",
  "Webflow",
  "Airtable",
  "Make",
  "Bubble",
  "Notion",
  "Google Sheets",
  "Shopify",
];

export const timezones = [
  { code: "UTC", value: "UTC" },
  { code: "EST", value: "America/New_York" },
  { code: "CST", value: "America/Chicago" },
  { code: "MST", value: "America/Denver" },
  { code: "PST", value: "America/Los_Angeles" },
  { code: "GMT", value: "Europe/London" },
  { code: "CET", value: "Europe/Paris" },
  { code: "EET", value: "Europe/Athens" },
  { code: "JST", value: "Asia/Tokyo" },
  { code: "CST", value: "Asia/Shanghai" },
  { code: "IST", value: "Asia/Kolkata" },
  { code: "AEST", value: "Australia/Sydney" },
  { code: "NZST", value: "Pacific/Auckland" },
  { code: "BRT", value: "America/Sao_Paulo" },
  { code: "ART", value: "America/Argentina/Buenos_Aires" },
  { code: "SAST", value: "Africa/Johannesburg" },
  { code: "MSK", value: "Europe/Moscow" },
  { code: "IST", value: "Asia/Jerusalem" },
  { code: "GST", value: "Asia/Dubai" },
  { code: "SGT", value: "Asia/Singapore" },
];

export const userCurrencies = [
  { code: "GBP", value: "GBP", name: "British Pound", symbol: "£" },
  { code: "USD", value: "USD", name: "United States Dollar", symbol: "$" },
  { code: "EUR", value: "EUR", name: "Euro", symbol: "€" },
];
